version: '2'

services:
  haushaltsbuch:
    image: haushaltsbuch/service:test
    expose:
      - "8080"
      - "9990"
    ports:
      - "8080:8080"
      - "9990:9990"
    network_mode: "host"

  web:
    build:
      context: .
    image: haushaltsbuch/web:test
    ports:
      - "80:80"
#    depends_on:
#      - haushaltsbuch
    network_mode: "host"
