version: '2'

services:
  haushaltsbuch:
    image: haushaltsbuch/anwendung:latest
    expose:
      - "8080"
      - "9990"
    ports:
      - "8080:8080"
      - "9990:9990"
    network_mode: "host"

  web:
    build:
      context: .
    image: haushaltsbuch/web-proxy:latest
    ports:
      - "80:80"
    network_mode: "host"
